version: '3'
services:
  scsbx:
    build:
      context: .
    working_dir: /home/pwn
    container_name: scsbx
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "19001:9999"
    entrypoint: /etc/init.sh
