version: '3'
services:
  pwarmup:
    build:
      context: .
    working_dir: /home/pwn
    container_name: pwarmup
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9001:9999"
    entrypoint: /etc/init.sh
